# src/core/states.py
"""All conversation states in one place."""

# ─── Core States ───
NEW_USER = "NEW_USER"
ONBOARDING = "ONBOARDING"
IDLE = "IDLE"

# ─── Transaction Recording ───
RECORDING = "RECORDING"
AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
AWAITING_CORRECTION = "AWAITING_CORRECTION"

# ─── Debt / Credit ───
DEBT_RECORDING = "DEBT_RECORDING"
DEBT_CONFIRMING = "DEBT_CONFIRMING"
DEBT_PAYMENT = "DEBT_PAYMENT"

# ─── Catalog Setup ───
CATALOG_MENU = "CATALOG_MENU"
CATALOG_SETUP_PRODUCTS = "CATALOG_SETUP_PRODUCTS"
CATALOG_SETUP_DETAILS = "CATALOG_SETUP_DETAILS"
CATALOG_ORGANIZE = "CATALOG_ORGANIZE"
CATALOG_ADD_DATA = "CATALOG_ADD_DATA"

# ─── CRM Prompt ───
CRM_HINT = "CRM_HINT"

# ─── Export / Documents ───
EXPORTING = "EXPORTING"
INVOICING = "INVOICING"

# ─── Edit / Delete ───
EDITING = "EDITING"
EDIT_TRANSACTION = "EDIT_TRANSACTION"
DELETE_CONFIRM = "DELETE_CONFIRM"

# ─── Guided Recording (button-driven) ───
GUIDED_RECORDING = "GUIDED_RECORDING"

# ─── Groups ───
# States where tier/limit check should NOT apply
EXEMPT_STATES = {
    ONBOARDING, NEW_USER,
    AWAITING_CONFIRMATION, AWAITING_CORRECTION,
    CATALOG_MENU, CATALOG_SETUP_PRODUCTS, CATALOG_SETUP_DETAILS,
    CATALOG_ORGANIZE, CATALOG_ADD_DATA,
    EDITING, EDIT_TRANSACTION, DELETE_CONFIRM,
    EXPORTING, INVOICING,
    DEBT_RECORDING, DEBT_CONFIRMING, DEBT_PAYMENT,
    CRM_HINT, GUIDED_RECORDING,
}
